# Generated by Django 3.1.6 on 2021-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrailleText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('braille', models.CharField(max_length=50)),
                ('text_type', models.CharField(choices=[('letter', 'Letter'), ('number', 'Number'), ('word', 'Word')], max_length=50)),
            ],
        ),
    ]
